services:
  fe-stamping-new:
    build:
      context: .
      dockerfile: Dockerfile
    image: riankurniawan/fe-stamping:1.0.0
    container_name: fe-stamping-new
    restart: always
    ports:
      - 5173:80
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - iot-stamping-network
      
networks:
  iot-stamping-network:
    driver: bridge
